version: '3.7'

services:
  image-service:
    build: ./image-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./image-service/:/app/
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    ports:
      - "8181:8181"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - image-service